spring:
  config:
    activate:
      on-profile: oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/api/auth/oauth2/callback/google"
            client-name: Google
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID:}
            client-secret: ${FACEBOOK_CLIENT_SECRET:}
            scope: email,public_profile
            redirect-uri: "{baseUrl}/api/auth/oauth2/callback/facebook"
            client-name: Facebook
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v20.0/dialog/oauth
            token-uri: https://graph.facebook.com/v20.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
            user-name-attribute: id

app:
  oauth:
    enabled: true
